version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: regular
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    environment:
      - PYTHONPATH=/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  app-obfuscated:
    build:
      context: .
      dockerfile: Dockerfile
      target: obfuscated
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 